version: '3.5'

networks:
  confluent:
    name: confluent

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    networks:
      - confluent
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka3:
    image: confluentinc/cp-kafka:latest
    container_name: kafka3
    networks:
      - confluent
    depends_on:
      - zookeeper
    ports:
      - "19092:19092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092,CONNECTIONS_FROM_HOST://localhost:19092,CONNECTIONS_FROM_LAN://192.168.1.6:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT,CONNECTIONS_FROM_LAN:PLAINTEXT
